name: Build Project
on:
  pull_request:
    branches:
      - '*_dev'
  
  push:
    branches:
      - '*_dev'

jobs:
  build_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: echo "${{ secrets.DOTENVFILE }}" > .env
      - run: 'yarn install'
      #- run: 'yarn nx run-many --target=lint --all --parallel --skip-nx-cache'
      - run: 'yarn nx run-many --target=build --all --parallel --skip-nx-cache'
