name: Build and Deploy

on:
  push:
    branches:
      - '**/*_dev'
  pull_request:
    branches:
      - '**/*_dev'

jobs:
  all_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.DOTENVFILE }}" > .env
      - run: 'npm install'
      - run: 'npm run build'
