name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  all_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.DOTENVFILE }}" > .env
      - run: 'cd client && npm install'
      - run: 'cd client && npm run deploy -- -m "Deploy React app to GitHub Pages"'
