name: Test Project

on:
  push:
    branches:
      - '**/*_test'
  pull_request:
    branches:
      - '**/*_test'

jobs:
  all_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.DOTENVFILE }}" > .env
      - run: 'cd client && npm install'
      - run: 'cd client && npm run test'
